export const data = [
  {
    id: 1,
    img: '',
    author: 'Adam Sendler',
    title: 'Solutions for people like you like people',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Id corporis eveniet et iste impedit, deserunt aut doloremque consequatur placeat quas!',
    category: 'people',
  },
  {
    id: 2,
    img: 'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    author: 'Adam Sendler',
    title: 'Solutions for people like you like people',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Id corporis eveniet et iste impedit, deserunt aut doloremque consequatur placeat quas!',
    category: 'marketing',
  },
  {
    id: 3,
    img: '',
    author: 'Adam Sendler',
    title: 'Solutions for people like you like people',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Id corporis eveniet et iste impedit, deserunt aut doloremque consequatur placeat quas!',
    category: 'marketing',
  },
  {
    id: 4,
    img: 'https://images.pexels.com/photos/2033997/pexels-photo-2033997.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
    author: 'Adam Sendler',
    title: 'Solutions for people like you like people',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Id corporis eveniet et iste impedit, deserunt aut doloremque consequatur placeat quas!',
    category: 'business',
  },
  {
    id: 5,
    img: '',
    author: 'Adam Sendler',
    title: 'Solutions for people like you like people',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Id corporis eveniet et iste impedit, deserunt aut doloremque consequatur placeat quas!',
    category: 'marketing',
  },
  {
    id: 6,
    img: '',
    author: 'Adam Sendler',
    title: 'Solutions for people like you like people',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Id corporis eveniet et iste impedit, deserunt aut doloremque consequatur placeat quas!',
    category: 'marketing',
  },
];
